### ISSUE TITLE
The latest version of the problem

### ISSUE THREAD

**Issue by xiebinJava** [Ingenico-ePayments/connect-sdk-client-ios#1]
1：Latest version can not enter the list of credit cards

2：Credit card number verification error

[GCAFNetworkingWrapper getResponseForURL:headers:additionalAcceptableStatusCodes:succes:failure:]_block_invoke.30 [Line 44] Error while retrieving response for URL https://api-us.globalcollect.com/client/v1/8481-b94d888b27e840bfb4a8c4221a67e0cf/productgroups?countryCode=MW&currencyCode=GBP&amount=6306&hide=fields&isRecurring=false: Request failed: not found (404)

the version 1.1.0 is OK
Please amend as soon as possible
thanks !!

**Comment by rob-spoor** [comment]
Grouping functionality is not yet available on production. It is available on the sandbox environment though.

**Comment by xiebinJava** [comment]
Is there a bug in the previous version?Can this run in production mode？

**Comment by rob-spoor** [comment]
The release notes only mention one fix, and only for the example app. You should be able to use version 1.1.0 of the SDK against production.

**Comment by xiebinJava** [comment]
OK Thanks ！！！

**Comment by josercc** [comment]
Request ICPaymentProduct https://ams1.preprod.api-ingenico.com/client/v1/328-3545c05225c14d43987d407718d0b3fe/products/1/?countryCode=IN&locale=en_US&currencyCode=INR&amount=1310&isRecurring=false&forceBasicFlow=true Error 404 @rob-spoor

**Comment by josercc** [comment]
![image](https://user-images.githubusercontent.com/4713847/47077595-df84fd80-d233-11e8-9489-68d74afe2adb.png)

**Comment by ronaldmiddelkoop** [comment]
Hi @josercc , looks like payment product 1 (visa) is not configured for your merchant in the payment context (country, currency, amount) you provided. To confirm this, you could do a Get Payment Products with that same context. This will list the products that are available.

**Comment by josercc** [comment]
@ronaldmiddelkoop 

![image](https://user-images.githubusercontent.com/4713847/47080898-c54f1d80-d23b-11e8-8f90-a08977e00dbc.png)


This will report a validation error

**Comment by ronaldmiddelkoop** [comment]
Hi @josercc , I'm not sure what you're showing me here?
