### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by tazihosniomar** [Ingenico-ePayments/connect-sdk-client-ios#10]
Hello,
We are using carthage for dependency management and we want to use Ingenico-ePayments but it seems like your framework doesn't support Carthage.

thank you in advance.

**Comment by ronaldmiddelkoop** [comment]
Hi omar, we haven't looked at Carthage yet I'm afraid. We'll need some time to investigate what it would take to add support for it.

**Comment by rob-spoor** [comment]
The latest release should support Carthage. Please let us know if it doesn't.
