### ISSUE TITLE
Need-help: cann't get accountOnFile array items

### ISSUE THREAD

**Issue by Mactub07** [Ingenico-ePayments/connect-sdk-client-ios#11]
Hi, I'm using pre-production Ogone account, want to implement `AccountOnFile flow`; 
my steps: 
- set paymentRequest.tokenize = YES;
- process order payment flow (paymentStatus - 9-Payment requested);
- proxy server api return response with `token`

issue: I cann't get accountOnFile: array is always empty;
for testing I'm using Visa card 4111 1111 1111 1111

**Comment by ronaldmiddelkoop** [comment]
Hi Mactub07, when you say "array is always empty", which array do you mean exactly?

**Comment by Mactub07** [comment]
good morning, @ronaldmiddelkoop , I mean array `ccountsOnFile` inside paymentProduct with specific ID. Thanks for quick feedback. Seems I resolved issue by myself. Problem was that I didn't pass valid tokens when initialize session on proxy backend , so session was created without tokens and accountsOnFile was empty
