### ISSUE TITLE
Deprecated UIWebView warning caused by AFNetworking/UIKit dependency

### ISSUE THREAD

**Issue by mgbrants** [Ingenico-ePayments/connect-sdk-client-ios#13]
Apple will deprecate UIWebView soon. Can the UIWebView dependency be removed from the SDK?

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by LeonStemerdink** [comment]
Hello mgbrants,

Thank you for reporting this issue with us. 
We are aware that Apple has deprecated the UIWebView APIs. We are investigating how we should remove them from the project.

**Comment by rob-spoor** [comment]
Since version 5.0.0, AFNetworking has been removed as dependency. Does that solve your issue?
