### ISSUE TITLE
Podinstall error

### ISSUE THREAD

**Issue by PatrickVanOverdijk** [Ingenico-ePayments/connect-sdk-client-ios#2]
When I try to use the cocoapods installtion I get the error that the pod specification cannot be found.

I can't find the pod on the cocoapods website either.

**Comment by rob-spoor** [comment]
The documentation is ahead of reality - the SDK isn't available on cocoapods yet. You will need to manually install the SDK from its source.

**Comment by rob-spoor** [comment]
FYI, version 3.0.1 of the SDK is now available on Cocoapods.
