### ISSUE TITLE
RBA_SDK Crash

### ISSUE THREAD

**Issue by puttputt** [Ingenico-ePayments/connect-sdk-client-ios#3]
Apologies if this is completely unrelated. But I'm working in a codebase that uses Ingenico devices and I am experiencing a crash with the RBA_SDK. I'm not exactly sure where this framework was from, or who developed it. But the little documentation I have has the Ingenico name on it.

Is this framework deprecated? Has it been replaced with the connect SDK?

> Crashed: com.apple.root.background-qos
> 0  RQMobile                       0x1005fe124 PacketManager::Status() (PacketManager.cpp:105)
> 1  RQMobile                       0x10061779c +[RBA_SDK GetConnectionStatus](RBA_SDK.m:190)
> 2  RQMobile                       0x1004744f0 -[IngenicoController sendDataToDevice:](IngenicoController.m:1690)
> 3  RQMobile                       0x100437cfc __64-[PayService InitializeDeviceWithEnableEmv:Progress:Completion:]_block_invoke_2 (PayService.m:194)
> 4  RQMobile                       0x1002821b4 __87-[PayMessageHandler sendMessage:IsInitializing:DeviceDataResponse:Progress:Completion:]_block_invoke (PayMessageHandler.m:123)
> 5  libdispatch.dylib              0x1820294bc _dispatch_call_block_and_release + 24
> 6  libdispatch.dylib              0x18202947c _dispatch_client_callout + 16
> 7  libdispatch.dylib              0x182037914 _dispatch_root_queue_drain + 2140
> 8  libdispatch.dylib              0x1820370b0 _dispatch_worker_thread3 + 112
> 9  libsystem_pthread.dylib        0x182241470 _pthread_wqthread + 1092
> 10 libsystem_pthread.dylib        0x182241020 start_wqthread + 4
> `

**Comment by ronaldmiddelkoop** [comment]
Hi puttputt, 

I'm afraid Connect and RBA are unrelated. Connect is for integration with the Ingenico ECommerce solution, whereas RBA (from the looks of it) is for Mobile Point of Sale. While it's not impossible that Connect will support mobile POS in the future, for now there isn'much this forum can do to help you. I'll try to find someone within Ingenico to pass your question on to.

Good luck,
Ronald

**Comment by puttputt** [comment]
Thanks Ronald,

I didn't think so. I haven't been able to find any resources or contacts for RBA so I appreciate you trying to help me out.
