### ISSUE TITLE
Swift compatibility

### ISSUE THREAD

**Issue by davidtperk** [Ingenico-ePayments/connect-sdk-client-ios#4]
I'm trying to use the GlobalCollectSDK in my Swift project, but there doesn't seem to be a master header file to import. Must I import every .h file from the SDK into my Swift bridging header?

**Comment by davidtperk** [comment]
Seems best to import only the related SDK components.

**Comment by dotliebrand** [comment]
Did you install the SDK using cocoapods? This should have installed all the necessary headers?

**Comment by davidtperk** [comment]
@dotliebrand the pod 'connect-sdk-client-ios' doesn't seem to exist anymore.

**Comment by rob-spoor** [comment]
It has actually never been uploaded as of yet.

**Comment by dotliebrand** [comment]
My bad, I thought it was. Rob is right.

**Comment by ronaldmiddelkoop** [comment]
Hi dtp5, this won't help you immediately, but we are working on the cocaopods upload. Also, we have a Swift SDK on our radar that will make your life easier in the future. No definitive release date yet though.

**Comment by rob-spoor** [comment]
Version 3.0.1 of the SDK is now available on [Cocoapods](https://cocoapods.org/?q=ingenico). It's renamed to `IngenicoConnectSDK` though.
