### ISSUE TITLE
IPP 320

### ISSUE THREAD

**Issue by amjad** [Ingenico-ePayments/connect-sdk-client-ios#5]
Does this allow integration for IPP 320 and iOS?

**Comment by rikvanthof** [comment]
No, these SDKs are targeting Ingenico ePayments and its e-commerce platforms and they can't be used  with any Ingenico terminals. These SDKs allow you to accept card not present transactions and require an account at Ingenico ePayments. Please see https://developer.globalcollect.com for more information on the capabilities.

**Comment by amjad** [comment]
Thanks. Any idea where I can get iOS SDK for the IPP320

**Comment by ebomcke-ingenico** [comment]
Hi @amjad,

I'm afraid I don't know exactly where you would be able to find such an SDK. I recommend that you head to the developer portal of the Telium TETRA platform (https://developer.ingenico.com/hc/en-gb/), they will be best placed to help you.
Best,
Etienne Bömcke
Product Manager - Connect API & SDKs

**Comment by amjad** [comment]
Thanks, I have found the SDKs for the integration. Thanks for your help.

**Comment by ghost** [comment]
hi @amjad , could you share the link for the SDKs you've found for an integration?
Thanks in advance

**Comment by amjad** [comment]
I received it from my payment processor.

**Comment by lyhuuloi** [comment]
> I received it from my payment processor.

@amjad Bro, can you please share it for me? I also need it for my device iPP350.

**Comment by amjad** [comment]
You will have to check with the payment processor you are integrating with. They provide gateway specific SDK.
