### ISSUE TITLE
Pod Install Issue

### ISSUE THREAD

**Issue by applebyte1992** [Ingenico-ePayments/connect-sdk-client-ios#6]
Hi I want to integrate your SDK in our application and get the pod installation command form link below
https://cocoapods.org/?q=ingenic
Below is the pod file code for my project

target 'SamplePayment' do
  Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

   Pods for SamplePayment
  pod 'IngenicoConnectSDK', '~> 3.0'

end

This is the response that I'll get when I run Pod install command. Can you please help me in this
Analyzing dependencies
[!] Unable to find a specification for `IngenicoConnectSDK (~> 3.0)

**Comment by LeonStemerdink** [comment]
Hello AppleByte,

I had the same issue. After running a `pod repo update` however (as found [here ](http://stackoverflow.com/questions/28844013/cocoapods-unable-to-find-a-specification-for-github-framework) on StackOverflow (in the comment)), the `pod install` command ran without issues. Have you tried this?

**Comment by applebyte1992** [comment]
Thanks @LeonStemerdink  
Issue is resolved with this. Please mention that in your read me so that it will help the developers to solve this problem.
