### ISSUE TITLE
Issue connecting to iOS9 

### ISSUE THREAD

**Issue by arjunkalburgi** [Ingenico-ePayments/connect-sdk-client-ios#7]
Hey I'm using `RBA_SDK Connect` once I've connected my iOS device to an ingenico bluetooth scanner via bluetooth. 

The ingenico device is connected via bluetooth in the Settings but `RBA_SDK Connect` is returning -103 (RESULT_ERROR_NOT_CONNECTED). 

This error is only occuring on our ios9.3 testing device. Wondering if anyone can provide insight?

**Comment by rikvanthof** [comment]
Could you provide some more information on what you are trying to accomplish and what is going wrong? Based on your last comment I take it that it does seem to work on other devices running a different version of iOS?

The SDK itself is used to communicate with Ingenico ePayments to retrieve relevant data on what can be offered to the user in terms of payment products and what to capture in terms of data for each of these. Lastly it can encrypt the captured input using the public key that it can retrieve from Ingenico ePayments.

Our SDK isn't using any bluetooth connections, but I guess that this is something that you have built yourself.

**Comment by maarten-daalder-isaac** [comment]
Hi @askalburgi,

I think you got the wrong SDK here, this is for the Ingenico Connect SDK (for e-commerce) and not a Point of Sale device.

Not sure if this is RBA, but you could try here: https://developer.ingenico.com/hc/en-gb/ (from #5).

**Comment by arjunkalburgi** [comment]
Oh hey sorry, yeah I think you're right I have the wrong SDK. Deepest apologies :)
