### ISSUE TITLE
AFNetworking compatibility issue

### ISSUE THREAD

**Issue by antwllm** [Ingenico-ePayments/connect-sdk-client-ios#8]
```
[!] Unable to satisfy the following requirements:
- `AFNetworking (~> 3.0)` required by `Podfile`
- `AFNetworking (~> 2.5.3)` required by `IngenicoConnectSDK (3.0.1)`
```

My project is currently using AFNetworking 3.1.0 via CocoaPods.

**Comment by rob-spoor** [comment]
The SDK currently requires version 2.5.3. Can you try downgrading the version of AFNetworking you use? Upgrading the required version of the SDK means bumping the minimal iOS version from 6 to 7, and that's something we cannot do at this point of time.

**Comment by rob-spoor** [comment]
For an overview of the minimal required versions for AFNetworking, please check out the Requirements table at https://cocoapods.org/pods/AFNetworking/.

**Comment by antwllm** [comment]
Hi @rob-spoor,

Thank you for your feedback. 

We will try that

**Comment by antwllm** [comment]
Hi @rob-spoor,

The downgrade will need a big amount of changes in the project. A solution will be to build the SDK as framework so in that case, AFNetworking will be embedded inside.

**Comment by rob-spoor** [comment]
We will see what's possible here, but that won't give a short-term solution. Perhaps you can include the SDK's `IngenicoConnectSDK` folder as a source folder of your project. That was the suggested way before the SDK was published on Cocoapods.

**Comment by antwllm** [comment]
We have tried but we had to modify the SDK to make it work.

Do you still have the instructions somewhere ? I will test it one more time with my team.

**Comment by rob-spoor** [comment]
You could try release 2.0.0, that includes the old README.md file.

**Comment by rob-spoor** [comment]
Since version 5.0.0, AFNetworking has been removed as dependency. Does that solve your issue?
